
// Objective-C API for talking to the following Go packages
//
//	github.com/bitcoinerlab/bitbox-react-native/native/go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bitboxnative_FRAMEWORK_H__
#define __Bitboxnative_FRAMEWORK_H__

#include "BitcoinerlabBitBoxBitboxnative.objc.h"
#include "Universe.objc.h"

#endif
