// Objective-C API for talking to github.com/bitcoinerlab/bitbox-react-native/native/go Go package.
//   gobind -lang=objc -prefix="BitcoinerlabBitBox" github.com/bitcoinerlab/bitbox-react-native/native/go
//
// File is generated by gobind. Do not edit.

#ifndef __BitcoinerlabBitBoxBitboxnative_H__
#define __BitcoinerlabBitBoxBitboxnative_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class BitcoinerlabBitBoxBitboxnativeClient;
@protocol BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation;
@class BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation;
@protocol BitcoinerlabBitBoxBitboxnativeMobileTransport;
@class BitcoinerlabBitBoxBitboxnativeMobileTransport;

@protocol BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation <NSObject>
- (BOOL)confirmPairingCode:(NSString* _Nullable)code ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)showPairingCode:(NSString* _Nullable)code deviceVerified:(BOOL)deviceVerified error:(NSError* _Nullable* _Nullable)error;
@end

@protocol BitcoinerlabBitBoxBitboxnativeMobileTransport <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(long)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Client wraps a single upstream BitBox firmware device session.
 */
@interface BitcoinerlabBitBoxBitboxnativeClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewClient creates a disconnected client wrapper. Platform native code should
use NewClientWithMobileTransport once it has opened a real transport.
 */
- (nullable instancetype)init;
/**
 * NewClientWithMobileTransport creates and initializes a BitBox client using a
platform-provided transport. productString may be the BitBox USB product
string or the short BitBox Nova BLE product string. If productString and
versionString are empty, the firmware API infers them through OP_INFO during
initialization, which is suitable for modern USB devices.
 */
- (nullable instancetype)initWithMobileTransport:(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable)transport productString:(NSString* _Nullable)productString versionString:(NSString* _Nullable)versionString isBluetooth:(BOOL)isBluetooth;
/**
 * NewClientWithMobileTransportAndPairing creates a client and routes app-side
pairing confirmation through pairingConfirmation. This is required for USB,
where there is no secure OS transport pairing layer around the Noise channel.
 */
- (nullable instancetype)initWithMobileTransportAndPairing:(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable)transport productString:(NSString* _Nullable)productString versionString:(NSString* _Nullable)versionString isBluetooth:(BOOL)isBluetooth pairingConfirmation:(id<BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation> _Nullable)pairingConfirmation;
/**
 * NewClientWithMobileTransportAndPairingConfig creates a client with app-side
pairing confirmation and a persisted Noise config file.
 */
- (nullable instancetype)initWithMobileTransportAndPairingConfig:(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable)transport productString:(NSString* _Nullable)productString versionString:(NSString* _Nullable)versionString isBluetooth:(BOOL)isBluetooth pairingConfirmation:(id<BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation> _Nullable)pairingConfirmation configPath:(NSString* _Nullable)configPath;
/**
 * BTCAddress delegates address retrieval/display to upstream bitbox02-api-go.
 */
- (NSString* _Nonnull)btcAddress:(NSString* _Nullable)apiNetwork keypath:(NSString* _Nullable)keypath scriptConfigJSON:(NSString* _Nullable)scriptConfigJSON display:(BOOL)display error:(NSError* _Nullable* _Nullable)error;
/**
 * BTCIsScriptConfigRegistered checks registration through upstream bitbox02-api-go.
 */
- (BOOL)btcIsScriptConfigRegistered:(NSString* _Nullable)apiNetwork scriptConfigJSON:(NSString* _Nullable)scriptConfigJSON keypathAccount:(NSString* _Nullable)keypathAccount ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * BTCRegisterScriptConfig delegates script config registration to upstream bitbox02-api-go.
 */
- (BOOL)btcRegisterScriptConfig:(NSString* _Nullable)apiNetwork scriptConfigJSON:(NSString* _Nullable)scriptConfigJSON keypathAccount:(NSString* _Nullable)keypathAccount xpubType:(NSString* _Nullable)xpubType name:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
/**
 * BTCSignMessage signs a Bitcoin message through upstream bitbox02-api-go.
 */
- (NSString* _Nonnull)btcSignMessage:(NSString* _Nullable)apiNetwork scriptConfigWithKeypathJSON:(NSString* _Nullable)scriptConfigWithKeypathJSON message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
/**
 * BTCSignPSBT parses, signs, and serializes a base64 PSBT through upstream bitbox02-api-go.
 */
- (NSString* _Nonnull)btcSignPSBT:(NSString* _Nullable)apiNetwork psbtBase64:(NSString* _Nullable)psbtBase64 forceScriptConfigJSON:(NSString* _Nullable)forceScriptConfigJSON formatUnit:(NSString* _Nullable)formatUnit error:(NSError* _Nullable* _Nullable)error;
/**
 * BTCXPub delegates xpub retrieval to upstream bitbox02-api-go.
 */
- (NSString* _Nonnull)btcxPub:(NSString* _Nullable)apiNetwork keypath:(NSString* _Nullable)keypath xpubType:(NSString* _Nullable)xpubType display:(BOOL)display error:(NSError* _Nullable* _Nullable)error;
/**
 * Close closes the active BitBox session if one is connected.
 */
- (void)close;
/**
 * Product returns the canonical upstream BitBox product identifier.
 */
- (NSString* _Nonnull)product:(NSError* _Nullable* _Nullable)error;
/**
 * RootFingerprint returns the connected device root fingerprint as lowercase hex.
 */
- (NSString* _Nonnull)rootFingerprint:(NSError* _Nullable* _Nullable)error;
/**
 * Version returns the connected device firmware version.
 */
- (NSString* _Nonnull)version:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewClient creates a disconnected client wrapper. Platform native code should
use NewClientWithMobileTransport once it has opened a real transport.
 */
FOUNDATION_EXPORT BitcoinerlabBitBoxBitboxnativeClient* _Nullable BitcoinerlabBitBoxBitboxnativeNewClient(void);

/**
 * NewClientWithMobileTransport creates and initializes a BitBox client using a
platform-provided transport. productString may be the BitBox USB product
string or the short BitBox Nova BLE product string. If productString and
versionString are empty, the firmware API infers them through OP_INFO during
initialization, which is suitable for modern USB devices.
 */
FOUNDATION_EXPORT BitcoinerlabBitBoxBitboxnativeClient* _Nullable BitcoinerlabBitBoxBitboxnativeNewClientWithMobileTransport(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable transport, NSString* _Nullable productString, NSString* _Nullable versionString, BOOL isBluetooth, NSError* _Nullable* _Nullable error);

/**
 * NewClientWithMobileTransportAndPairing creates a client and routes app-side
pairing confirmation through pairingConfirmation. This is required for USB,
where there is no secure OS transport pairing layer around the Noise channel.
 */
FOUNDATION_EXPORT BitcoinerlabBitBoxBitboxnativeClient* _Nullable BitcoinerlabBitBoxBitboxnativeNewClientWithMobileTransportAndPairing(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable transport, NSString* _Nullable productString, NSString* _Nullable versionString, BOOL isBluetooth, id<BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation> _Nullable pairingConfirmation, NSError* _Nullable* _Nullable error);

/**
 * NewClientWithMobileTransportAndPairingConfig creates a client with app-side
pairing confirmation and a persisted Noise config file.
 */
FOUNDATION_EXPORT BitcoinerlabBitBoxBitboxnativeClient* _Nullable BitcoinerlabBitBoxBitboxnativeNewClientWithMobileTransportAndPairingConfig(id<BitcoinerlabBitBoxBitboxnativeMobileTransport> _Nullable transport, NSString* _Nullable productString, NSString* _Nullable versionString, BOOL isBluetooth, id<BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation> _Nullable pairingConfirmation, NSString* _Nullable configPath, NSError* _Nullable* _Nullable error);

@class BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation;

@class BitcoinerlabBitBoxBitboxnativeMobileTransport;

/**
 * MobilePairingConfirmation lets platform code show and confirm a BitBox Noise
pairing code. ShowPairingCode must return quickly; ConfirmPairingCode may
block until the user accepts or rejects the code in the app UI.
 */
@interface BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation : NSObject <goSeqRefInterface, BitcoinerlabBitBoxBitboxnativeMobilePairingConfirmation> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)confirmPairingCode:(NSString* _Nullable)code ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)showPairingCode:(NSString* _Nullable)code deviceVerified:(BOOL)deviceVerified error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * MobileTransport is implemented by platform native code and provides raw U2F
HID report reads and writes over the platform transport, such as iOS BLE.
 */
@interface BitcoinerlabBitBoxBitboxnativeMobileTransport : NSObject <goSeqRefInterface, BitcoinerlabBitBoxBitboxnativeMobileTransport> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(long)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

#endif
